### ISSUE TITLE
Weird dialog

### ISSUE THREAD

**Issue by retog** [plazi/GoldenGATE-Editor#1]
I find this dialog somewhat confusing:

![image](https://user-images.githubusercontent.com/110756/101015956-6d351b80-3568-11eb-9f70-f57e189e3b22.png)

I just started GoldenGATE Editor, chose a configuration, and agreed to update the outdated local configuration.

**Comment by gsautter** [comment]
Oh, this is a feature I put in only later, and I think so far we have only updated existing installations since ... sorry about this, you can simply hit cancel there, as there is no cached data so far. I'll add a respective check.
